### ISSUE TITLE
flutter_pd support for iOS

### ISSUE THREAD

**Issue by Jiffer** [niusounds/flutter_pd#1]
Hello! I'm happy to see you were able to use libPd with Flutter on Android. I am planning on developing a project that will use Flutter + libPd for both Android and iOS. I am curious if you had any successes or known issues when implementing this on iOS. Any other information you can share would be much appreciated.
All the Best,
Jiffer

ps - sorry to file this as an issues - I didn't see another way to contact you about this

**Comment by niusounds** [comment]
sorry to late reply!

I have implemented Swift side just now!
Code refactoring is still required but example project is works on iOS simulator.

**Comment by Jiffer** [comment]
amazing, I will take a look!

**Comment by Jiffer** [comment]
I have been using the flutter_pd with iOS for a while and so far it seems to be very stable. I have some questions about sending messages from Pd to flutter but the basics of Pd in flutter for iOS are working.
